import { DevtoolsProvider } from "@providers/devtools";
import { Refine } from "@refinedev/core";
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar";
import {
  RefineSnackbarProvider,
  useNotificationProvider,
} from "@refinedev/mui";
import { Box, Typography } from "@mui/material";

import ComputerRoundedIcon from "@mui/icons-material/ComputerRounded";
import ApiIcon from "@mui/icons-material/Api";

import routerProvider from "@refinedev/nextjs-router";
import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { Suspense } from "react";

import { AppIcon } from "@components/app-icon";
import { ColorModeContextProvider } from "@contexts/color-mode";
import { authProviderClient } from "@providers/auth-provider/auth-provider.client";
import { dataProvider } from "@providers/data-provider";
import DashboardIcon from "@mui/icons-material/Dashboard";
import AnalyticsIcon from "@mui/icons-material/Analytics";
import TaskAltIcon from "@mui/icons-material/TaskAlt";
import ManageSearchIcon from "@mui/icons-material/ManageSearch";
import HelpIcon from "@mui/icons-material/Help";
import SettingsIcon from "@mui/icons-material/Settings";
import "./style.css";

export const metadata: Metadata = {
  title: "BestHub",
  description: "Generated by Best",
  icons: {
    icon: "/favicon.ico",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const theme = cookieStore.get("theme");
  const defaultMode = theme?.value === "dark" ? "dark" : "light";

  return (
    <html lang="ru">
      <body>
        <Suspense>
          <RefineKbarProvider>
            <ColorModeContextProvider defaultMode={defaultMode}>
              <RefineSnackbarProvider>
                <DevtoolsProvider>
                  <Refine
                    routerProvider={routerProvider}
                    dataProvider={dataProvider}
                    notificationProvider={useNotificationProvider}
                    authProvider={authProviderClient}
                    resources={[
                      //   {
                      //     name: "blog_posts",
                      //     list: "/blog-posts",
                      //     create: "/blog-posts/create",
                      //     edit: "/blog-posts/edit/:id",
                      //     show: "/blog-posts/show/:id",
                      //     meta: {
                      //       canDelete: true,
                      //     },
                      //   },
                      //   {
                      //     name: "categories",
                      //     list: "/categories",
                      //     create: "/categories/create",
                      //     edit: "/categories/edit/:id",
                      //     show: "/categories/show/:id",
                      //     meta: {
                      //       canDelete: true,
                      //     },
                      //   },
                      {
                        name: "Программы",
                        list: "/programs",
                        icon: <ComputerRoundedIcon />,
                      },
                      {
                        name: "API",
                        list: "/api",
                        icon: <ApiIcon />,
                      },
                      {
                        name: "Панель администратора",
                        list: "/dashboard",
                        icon: <DashboardIcon />,
                      },
                      {
                        name: "Аналитика",
                        list: "/analytics",
                        icon: <AnalyticsIcon />,
                      },
                      {
                        name: "Задачи",
                        list: "/tasks",
                        icon: <TaskAltIcon />,
                      },
                      {
                        name: "История",
                        list: "/history",
                        icon: <ManageSearchIcon />,
                      },
                      {
                        name: "Поддержка",
                        list: "/helper",
                        icon: <HelpIcon />,
                      },
                      {
                        name: "Настройки ",
                        list: "/settings",
                        icon: <SettingsIcon />,
                      },
                    ]}
                    options={{
                      syncWithLocation: true,
                      warnWhenUnsavedChanges: true,
                      useNewQueryKeys: true,
                      projectId: "5TAvqo-nlABPq-pdDwTk",
                      title: { text: "BestHub", icon: <AppIcon /> },
                    }}
                  >
                    {children}
                    <RefineKbar />
                  </Refine>
                  <Typography
                    className="BrandsTextAnimation"
                    sx={{
                      display: "inline",
                      position: "sticky",
                      zIndex: 10000,
                      bottom: "10px",
                      left: "49px",
                    }}
                  ></Typography>
                </DevtoolsProvider>
              </RefineSnackbarProvider>
            </ColorModeContextProvider>
          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>
  );
}
